#!/usr/bin/env sh

sudo yabai --load-sa

# Signal hooks
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=mission_control_exit action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_added action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_removed action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_created action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_destroyed action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_focused action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_moved action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_resized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_minimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_deminimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'

# Create managed spaces
"$HOME"/.config/yabai/create_spaces.sh

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice)$" manage=off
yabai -m rule --add app="^(iStat Menus|Stats|FaceTime|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off


yabai -m config window_border on                      \
                mouse_follows_focus off               \
                focus_follows_mouse off               \
                window_placement second_child         \
                window_topmost off                    \
                window_shadow float                   \
                window_opacity on                     \
                window_opacity_duration 0.15          \
                active_window_opacity 1.0             \
                normal_window_opacity 0.90            \
                window_border_width 2                 \
                window_border off                            \
                window_border_radius 11               \
                active_window_border_color 0xff7793d1 \
                normal_window_border_color 0xff5e6798 \
                insert_feedback_color 0xff7793d1      \
                split_ratio 0.50                      \
                auto_balance off                      \
                mouse_modifier alt                     \
                mouse_action1 move                    \
                mouse_action2 resize                  \
                mouse_drop_action warp                \
                layout bsp                            \
                top_padding 4                         \
                bottom_padding 4                      \
                left_padding 4                        \
                right_padding 4                       \
                window_gap 4

yabai -m config --space 6 layout float

echo "yabai configuration loaded.."
